### ISSUE TITLE
Home page UI

### ISSUE THREAD

**Issue by Rohit0301** [Rohit0301/CodingCombat#12]
Make a beautiful landing page with better UI

**Comment by nemynigam** [comment]
please elaborate more on this issue and i want to work on it

**Comment by AravindHari** [comment]
Hey, @Rohit0301 I would like to do the task

**Comment by bridyash13** [comment]
Hey can you please assign this issue to me

**Comment by Pranjalshivhare** [comment]
Currently I am working on the same so please assign it to me
