### ISSUE TITLE
create signup page

### ISSUE THREAD

**Issue by Rohit0301** [Rohit0301/CodingCombat#7]
Create a new signup page for this website

**Comment by ssurbhi09** [comment]
Can you assign me?

**Comment by B1TSH3LL** [comment]
Hlo I Can Work On This I Can Make More Attractive HTML Css And Js SignUp Page With Cool Animations Please Assign It To Me :)

**Comment by saritapatel8770** [comment]
Currently I am working on the same  so please assign it to me
